# SRG dla Forge 1.8.9 (produkcja). ZWERYFIKUJ w MCP mapping viewerze!
class.Minecraft=net.minecraft.client.Minecraft
class.EntityPlayerSP=net.minecraft.client.entity.EntityPlayerSP
class.Entity=net.minecraft.entity.Entity
class.EntityPlayer=net.minecraft.entity.player.EntityPlayer
class.EntityLivingBase=net.minecraft.entity.EntityLivingBase
class.EntityRenderer=net.minecraft.client.renderer.EntityRenderer
class.GuiScreen=net.minecraft.client.gui.GuiScreen
class.ItemStack=net.minecraft.item.ItemStack
class.ItemSword=net.minecraft.item.ItemSword
class.ItemAxe=net.minecraft.item.ItemAxe
class.MovingObjectPosition=net.minecraft.util.MovingObjectPosition
class.World=net.minecraft.world.World

m.Minecraft.getMinecraft=func_71410_x
m.Entity.getDistanceToEntity=func_70032_d
m.Minecraft.runTick=func_71407_l
m.Minecraft.displayGuiScreen=func_147108_a
m.Minecraft.clickMouse=func_147116_af
m.EntityRenderer.updateCameraAndRender=func_181560_a
m.EntityPlayerSP.onUpdate=func_70071_h_
m.Entity.setSprinting=func_70031_b
m.EntityLivingBase.getHeldItem=func_70694_bm
m.EntityPlayer.getHeldItem=getHeldItem
m.ItemStack.getItem=func_77973_b

f.Minecraft.thePlayer=field_71439_g
f.Minecraft.theWorld=field_71441_f
f.Minecraft.currentScreen=field_71462_r
f.Minecraft.leftClickCounter=field_71429_W
f.Entity.posX=field_70165_t
f.Entity.posY=field_70163_u
f.Entity.posZ=field_70161_v
f.EntityLivingBase.moveForward=field_70701_bs
f.Minecraft.objectMouseOver=field_71476_x
f.World.loadedEntityList=field_72996_f
f.Entity.rotationYaw=field_70177_z
f.MovingObjectPosition.typeOfHit=field_72313_a
