# Srodowisko deweloperskie (nazwy MCP). Brak wpisu m./f. => nazwa == klucz.
class.Minecraft=net.minecraft.client.Minecraft
class.EntityPlayerSP=net.minecraft.client.entity.EntityPlayerSP
class.Entity=net.minecraft.entity.Entity
class.EntityLivingBase=net.minecraft.entity.EntityLivingBase
class.EntityRenderer=net.minecraft.client.renderer.EntityRenderer
class.GuiScreen=net.minecraft.client.gui.GuiScreen
